name: Tests

on:
  push:
    branches: [ main, dev,]
  pull_request:
    branches: [ main, dev,]

permissions:
  contents: write

jobs:

  test:

    runs-on: ubuntu-latest
    environment : tests
    env:
      RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      RAPID_API_HOST: ${{ secrets.RAPID_API_HOST }}


    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.12",]
        # python-version: ["3.8.1", "3.9.1", "3.10.12", "3.11.1", "3.12.1"]
        poetry-version: ["1.7.0"]
        # pandas-version: ["2.2.0", "2.1.0", "2.0.0", "1.5.0", "1.4.0", "1.3.0"]
        # scikit-learn-version: ["1.4.0", "1.3.0", "1.2.0", "1.1.0", "1.0",]

    # runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: View poetry --help
        run: poetry --help

      - name: poetry Install
        run: poetry install --without doc,static

      - name: Valid secrets
        run: echo "${{ secrets.RAPID_API_HOST }}"

      - name: Run tests with pytest
        run: poetry run pytest -vvx --capture=tee-sys --log-cli-level=INFO tests/integration/
